apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: check-backups
  name: check-backups
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-backups
  template:
    metadata:
      labels:
        app: check-backups
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
        server-diag-port: "1444"
        server-identity: spiffe://vandry.org/ns/default/pod-label/app/check-backups
    spec:
      containers:
      - name: check-backups
        image: vandry/check_backups
        command:
        - "/check-backups"
        - "--s3-endpoint=https://sos-ch-gva-2.exo.io"
        - "--s3-region-name=ch-gva-2"
        - "--bucket-name=longhorn-backup"
        - "--diag-https-port=1444"
        - "--diag-http-port=9090"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
        volumeMounts:
          - name: s3-credentials
            readOnly: true
            mountPath: "/root/.aws"
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
            readOnly: true
        ports:
        - containerPort: 9090
        - containerPort: 1444
        env:
        - name: RUST_LOG
          value: info
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
      volumes:
        - name: s3-credentials
          secret:
            secretName: check-backups.s3.credentials
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
      restartPolicy: Always
